### ISSUE TITLE
スクリーンショットをじっくり見るページを作成

### ISSUE THREAD

**Issue by MeitoKuriyama** [waragaya1999/shinri_no_kagami#45]
スクショ撮った瞬間モーダルで見せてもいいし、リストページから飛んでくるようにしてもいいと思う

**Comment by waragaya1999** [comment]
記録しました的なトースト出して見たいなら記録ページ行ってもらう形式でいいんじゃね？

**Comment by MeitoKuriyama** [comment]
リストからロケーション消えたのって仕様？

**Comment by MeitoKuriyama** [comment]
#45-feature_photoPage
でvideoとcanvasを消す機能を追加したので見てみて！

**Comment by MeitoKuriyama** [comment]
なんかモーダルの方が取り回ししやすいかなって思ってモーダルにしちゃった
ページじゃなきゃダメだったらすぐ直すんでいってくダセェ
